import { describe, expect, it } from 'vitest';
import { ExportError, generateExport, answerToPlainText } from '@/lib/export';
import type { EvidenceRegion, Run } from '@/data/types';

const ALL_OPTIONS = {
  executionTrace: true,
  lowConfidenceRegions: true,
  modelVersions: true,
};

function region(overrides: Partial<EvidenceRegion> = {}): EvidenceRegion {
  return {
    id: 'R1',
    className: 'dense vegetation',
    area: '5.76 km²',
    perimeter: '24.00 km',
    confidence: 0.8,
    centroid: '28.7451N 104.7527W',
    bands: 'B04 B8A · NDVI',
    provenance: 'measured',
    box: { left: '0%', top: '0%', width: '10%', height: '10%' },
    geometry: {
      type: 'Polygon',
      coordinates: [
        [
          [-104.74, 28.75],
          [-104.75, 28.75],
          [-104.75, 28.76],
          [-104.74, 28.75],
        ],
      ],
    },
    ...overrides,
  };
}

function run(overrides: Partial<Run> = {}): Run {
  return {
    id: 'abc123',
    date: '2026-09-04',
    user: 'live',
    elapsed: '0.29 s',
    query: 'Where is the vegetation?',
    sceneId: 'scene-1',
    state: 'complete',
    confidence: 0.72,
    answer: [
      { t: 'text', value: 'Vegetation covers ' },
      { t: 'value', value: '16.59 km²', tone: 'measured' },
    ],
    regions: [region()],
    stages: [{ name: 'query understanding', state: 'done', duration: '0.00 s' }],
    ...overrides,
  };
}

async function readBlob(blob: Blob): Promise<string> {
  return new Uint8Array(await blob.arrayBuffer()).reduce(
    (text, byte) => text + String.fromCharCode(byte),
    '',
  );
}

describe('run export', () => {
  it('writes one CSV row per region with the measured values', async () => {
    const generated = await generateExport(run(), 'csv', ALL_OPTIONS);
    const csv = new TextDecoder().decode(await generated.blob.arrayBuffer());

    expect(generated.filename).toBe('satquery-run-abc123-measurements.csv');
    expect(csv).toContain('"region_id","class","area"');
    expect(csv).toContain('"R1","dense vegetation","5.76 km²"');
    expect(csv).toContain('Where is the vegetation?');
  });

  it('quotes CSV fields that contain a comma', async () => {
    const generated = await generateExport(
      run({ regions: [region({ area: '921,600 m²' })] }),
      'csv',
      ALL_OPTIONS,
    );
    const csv = new TextDecoder().decode(await generated.blob.arrayBuffer());

    expect(csv).toContain('"921,600 m²"');
  });

  it('reports a real sha256 of the generated bytes', async () => {
    const generated = await generateExport(run(), 'csv', ALL_OPTIONS);

    expect(generated.sha256).toMatch(/^[0-9a-f]{64}$/);
    expect(generated.byteLength).toBe(generated.blob.size);
  });

  it('builds a GeoJSON feature collection from the measured geometry', async () => {
    const generated = await generateExport(run(), 'bundle', ALL_OPTIONS);
    const bundle = JSON.parse(new TextDecoder().decode(await generated.blob.arrayBuffer()));

    expect(bundle.geojson.type).toBe('FeatureCollection');
    expect(bundle.geojson.crs).toBe('EPSG:4326');
    expect(bundle.geojson.features).toHaveLength(1);
    expect(bundle.geojson.features[0].geometry.coordinates[0][0]).toEqual([-104.74, 28.75]);
    expect(bundle.run.confidence).toBe(0.72);
    expect(bundle.execution_trace).toHaveLength(1);
  });

  it('omits the trace and plan when those options are off', async () => {
    const generated = await generateExport(run(), 'bundle', {
      ...ALL_OPTIONS,
      executionTrace: false,
      modelVersions: false,
    });
    const bundle = JSON.parse(new TextDecoder().decode(await generated.blob.arrayBuffer()));

    expect(bundle.execution_trace).toBeUndefined();
    expect(bundle.plan).toBeUndefined();
  });

  it('drops low-confidence regions when that option is off', async () => {
    const generated = await generateExport(
      run({ regions: [region(), region({ id: 'R2', confidence: 0.47 })] }),
      'csv',
      { ...ALL_OPTIONS, lowConfidenceRegions: false },
    );
    const csv = new TextDecoder().decode(await generated.blob.arrayBuffer());

    expect(csv).toContain('"R1"');
    expect(csv).not.toContain('"R2"');
  });

  it('refuses a GeoJSON bundle for a run with no measured geometry', async () => {
    const authored = run({ regions: [region({ geometry: undefined })] });

    await expect(generateExport(authored, 'bundle', ALL_OPTIONS)).rejects.toBeInstanceOf(
      ExportError,
    );
  });

  it('refuses a CSV when every region was filtered out', async () => {
    await expect(
      generateExport(run({ regions: [region({ confidence: 0.1 })] }), 'csv', {
        ...ALL_OPTIONS,
        lowConfidenceRegions: false,
      }),
    ).rejects.toBeInstanceOf(ExportError);
  });

  it('renders a real PDF document', async () => {
    const generated = await generateExport(run(), 'pdf', ALL_OPTIONS);

    expect(generated.filename).toBe('satquery-run-abc123-report.pdf');
    expect(await readBlob(generated.blob)).toMatch(/^%PDF-/);
    expect(generated.byteLength).toBeGreaterThan(1000);
  });

  it('flattens answer tokens into plain text', () => {
    expect(answerToPlainText(run().answer)).toBe('Vegetation covers 16.59 km²');
  });
});
